# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{html_namespacing}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["adamh"]
  s.date = %q{2010-11-04}
  s.description = %q{Inserts "class=" attributes within snippets of HTML so CSS and JavaScript can use automatic scopes}
  s.email = %q{adam@adamhooper.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
     "lib/html_namespacing.rb",
     "lib/html_namespacing/plugin.rb",
     "lib/html_namespacing/plugin/dom_scan_jquery.js",
     "lib/html_namespacing/plugin/dom_scan_jquery.js.compressed",
     "lib/html_namespacing/plugin/rails.rb",
     "lib/html_namespacing/plugin/sass.rb",
     "lib/html_namespacing/html_namespacing.jar"
  ]
  s.homepage = %q{http://github.com/adamh/html_namespacing}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Automatic HTML namespacing}
  s.test_files = [
     "spec/extension_spec.rb",
     "spec/spec_helper.rb"
  ]
end

